name: Publish Node package
description: GitHub Action that publishes compiled code to npm and similar package registries.
author: Jaid
runs:
  using: node12
  main: build/index.js
inputs:
  npmToken:
    description: Token for authorizing "npm publish" execution
  npmRegistry:
    description: Registry host for npm
    default: registry.npmjs.org
    required: true
  npmrcFile:
    description: File path to npmrc, relative to repository
    default: .npmrc
    required: true
branding:
  icon: box
  color: blue
