name: Publish Node package
description: GitHub Action that publishes compiled code to npm and similar package registries.
author: Jaid
runs:
  using: node12
  main: build/index.js
inputs:
  npmrcFile:
    description: File path to npmrc (relative to repository)
    default: .npmrc
    required: true
  publishDirectory:
    description: Directory with package contents (relative to repository)
    default: "."
    required: true
  npmPrepareScript:
    description: Name of an npm script entry (for example "build" to run package.json[build]) that will be executed before publishing
  ### npm
  npmToken:
    description: Token for authorizing "npm publish" execution for npm registry
  npmRegistry:
    description: Registry host for npm
    default: registry.npmjs.org
    required: true
  ### GitHub Packages
  githubToken:
    description: Token for authorizing "npm publish" execution for GitHub Packages registry
  githubRegistry:
    description: Registry host for GitHub Packages
    default: npm.pkg.github.com
    required: true
branding:
  icon: box
  color: blue
